<a href="https://colab.research.google.com/github/sydly148/hackthehood-buildfa25/blob/main/%5BBuild%5D_Week_5_Tiger_Teams_Intro_to_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Week 5 Tiger Teams — Intro to SQL

In today’s assignment, you'll learn the basics of SQL!




---

### Reference & AI Usage Policy
You’re encouraged to reference online documentation and resources such as:  
- [W3Schools](https://www.w3schools.com/python/)  
- [Stack Overflow](https://stackoverflow.com/questions/tagged/python)  
- Official library docs such as [pandas.pydata.org](https://pandas.pydata.org/docs/)  
- [SQL Documentation](https://www.w3schools.com/sql/sql_quickref.asp)   

You may also use **AI tools** (e.g., ChatGPT, Copilot, or Gemini) **as learning aids**, not as shortcuts to complete the assignment.

If you use AI, you must clearly comment **where and how** you used it — for example:  

```python
# Used ChatGPT to understand how to filter rows with .str.contains()

# 🔍 **Introduction: Why SQL?**

**Structured Query Language (SQL)** is a programming language used to **store, query, and manage data** in databases.

If Pandas is like Excel in Python, then SQL is like the **language that databases speak**.
While Pandas works with in-memory DataFrames, SQL works with tables stored in databases — but both share similar ideas:

*   Rows = records
*   Columns = fields

You can filter, sort, group, and join data — just like with Pandas!

In this assignment, you’ll:

1. Learn how to use **SQL in Google Colab**.

2. Compare **SQL queries** with familiar **Pandas operations**.

3. Write your own simple SQL queries!

The general syntax of a SQL query follows this form, though you may not need all of these arguments in every query you write:
```python
SELECT column1, column2, aggregate_function(column3), ...
FROM table_name
WHERE condition
GROUP BY column_name(s)
HAVING condition
ORDER BY column_name(s) [ASC | DESC];

## **Set Up**

In [ ]:
# Run this cell to import pandas and sqlite
import sqlite3
import pandas as pd

# Create a sample dataset
data = {
    "name": ["Alice", "Bob", "Charlie", "Diana", "Ethan"],
    "age": [24, 27, 22, 32, 29],
    "city": ["New York", "Los Angeles", "New York", "Chicago", "Chicago"],
    "score": [88, 92, 85, 79, 95]
}

df = pd.DataFrame(data)

# Create an in-memory SQLite database and load the dataframe
conn = sqlite3.connect(":memory:")
df.to_sql("students", conn, index=False, if_exists="replace")

# View the data
pd.read_sql("SELECT * FROM students", conn)

      name  age         city  score
0    Alice   24     New York     88
1      Bob   27  Los Angeles     92
2  Charlie   22     New York     85
3    Diana   32      Chicago     79
4    Ethan   29      Chicago     95

## **Step 1: Your First SQL Query**

In Pandas, you might filter rows like this to show only the rows in the DataFrame where the score is greater than 85:

```python
df[df["score"] > 85]

In SQL, you write:

```python
SELECT * FROM students WHERE score > 85;

This *selects* **all columns** (using *) *from* the **students** table *where* the **score > 85**.  

We will use the following syntax to display SQL queries using the read_sql method in the pandas library. Try running the cell below.

In [ ]:
pd.read_sql("SELECT * FROM students WHERE score > 85;", conn)

    name  age         city  score
0  Alice   24     New York     88
1    Bob   27  Los Angeles     92
2  Ethan   29      Chicago     95

# **Step 2: Practice Questions**

Use SQL queries to answer the following questions. You should use the following syntax for all of your queries:

```python
pd.read_sql("...", conn)

1. Select all students from Chicago.

2. Select only the names and scores of students from New York.

3. Find all students who are older than 25 years old.

4. Order all students by score from highest to lowest.

5. Find the average score of all students. You can use aggregate functions in the "SELECT" statement!

## **Step 3: Comparing SQL and Pandas**
Try writing **both SQL and Pandas** for the following exercise.

1. Get all students whose score is above 85 and live in New York.

In [ ]:
# SQL version:

In [ ]:
# Pandas version:

## **Step 4: Bad SQL Example**

Here's a "bad" SQL query:

In [ ]:
pd.read_sql("SELECT name, city score FROM students", conn)

      name        score
0    Alice     New York
1      Bob  Los Angeles
2  Charlie     New York
3    Diana      Chicago
4    Ethan      Chicago

**Answer the following questions**:
1. Does this cause an error or unexpected result?
2. How could you fix it?

## **Congratulations! You've finished the Week 5 Tiger Teams assignment. Don't forget to submit this assignment to Google Classroom.**